#!/usr/bin/env python
"""Render loops/student_v1/template_screen.md from outputs/student_v1/V4/screen.json (derived, R9)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCREEN = ROOT / "outputs" / "student_v1" / "V4" / "screen.json"
OUT = ROOT / "loops" / "student_v1" / "template_screen.md"


def fmt(value, digits: int = 4) -> str:
    return "n/a" if value is None else f"{value:.{digits}f}"


def main() -> None:
    report = json.loads(SCREEN.read_text(encoding="utf-8"))
    lines = [
        "# student_v1 — V4 template screen",
        "",
        "Generated by `scripts/student/v1_screen_report.py` from `outputs/student_v1/V4/screen.json`. Do not edit.",
        "",
        f"Rule: {report['rule']}. A bag-of-words classifier is fitted on each template's pre-window train "
        "items and scored on its pre-window dev items. The micro figure is shown for reference only.",
        "",
        "| template | source | qtype | train | dev | dev gold classes | BoW dev macro | BoW dev micro | gold-in-state | decision |",
        "|---|---|---|---:|---:|---:|---:|---:|---|---|",
    ]
    for tid, r in sorted(report["templates"].items()):
        flag = "flagged" if r["gold_in_state"].get("flagged") else "ok"
        decision = r["decision"] if not r["reasons"] else f"{r['decision']} ({', '.join(r['reasons'])})"
        lines.append(
            f"| `{tid}` | {r['source']} | {r['qtype']} | {r['n_train']} | {r['n_dev']} | "
            f"{len(r['dev_gold_classes'])} | {fmt(r['bow_dev_macro_accuracy'])} | "
            f"{fmt(r['bow_dev_micro_accuracy'])} | {flag} | {decision} |"
        )
    lines += ["", f"Kept: {len(report['kept'])}. Dropped: {len(report['dropped'])} "
              f"({', '.join(f'`{t}`' for t in report['dropped'])}).", ""]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
