#!/usr/bin/env python
"""Render loops/student_v1/V2_padding.md from the V2 artifacts (derived, never hand-edited).

Reads outputs/student_v1/V2/*.json and writes the committed aggregate report. Every number in the
report comes from one of those files; the report names the file it came from.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
V2 = ROOT / "outputs" / "student_v1" / "V2"
OUT = ROOT / "loops" / "student_v1" / "V2_padding.md"


def load(name: str) -> dict:
    return json.loads((V2 / name).read_text(encoding="utf-8"))


def probe_row(label: str, name: str) -> str:
    d = load(name)
    padded = d["alone_vs_left_padded_batch"]["max_abs_delta"]
    control = d["alone_vs_uniform_batch_control"]["max_abs_delta"]
    prec = d.get("precision") or {}
    tf32 = "on" if prec.get("cudnn_allow_tf32") else ("off" if prec else "not recorded")
    return (f"| {label} | `{name}` | {padded:.3e} | {control:.3e} | {d['verdict']} | {tf32} |")


def main() -> None:
    effect = load("effect.json")
    logit = load("logit_control_strict_fp32.json")
    shape = load("shape_control_strict_fp32.json")
    rederive = (V2 / "rederive_effect.txt").read_text(encoding="utf-8").strip().splitlines()[-1]
    comp = effect["comparisons"]["unpadded1-old"]
    scor = effect["scorings"]
    inputs = effect["inputs"]

    def pts(d: dict) -> str:
        return f"{d['point'] * 100:+.3f} pts, 95% CI [{d['ci_lo'] * 100:+.3f}, {d['ci_hi'] * 100:+.3f}] (n={d['n']})"

    top = sorted(comp["per_template"].items(), key=lambda kv: -abs(kv[1]["accuracy_diff"]["point"]))[:5]
    top_rows = "\n".join(
        f"| `{t}` | {s['n']} | {s['accuracy_diff']['point'] * 100:+.2f} | "
        f"[{s['accuracy_diff']['ci_lo'] * 100:+.2f}, {s['accuracy_diff']['ci_hi'] * 100:+.2f}] | "
        f"{s['argmax_changed']} | {s['correct_to_wrong']} / {s['wrong_to_correct']} |"
        for t, s in top
    )
    lines = [
        "# student_v1 — V2: padding fix and its measured effect",
        "",
        "Generated by `scripts/student/v2_report.py` from `outputs/student_v1/V2/*.json`. Do not edit by hand.",
        "",
        "## Status: BLOCKED (acceptance item 1)",
        "",
        "The ADVISORY acceptance requires the trained-checkpoint padded-batch test to pass at a tolerance of "
        "1e-3 (8 dev items, fp32, alone vs padded batch). It does not pass with the fix. The tolerance was "
        "not changed. The residual is at the level of pure sequence-length shape noise, so no padded "
        "configuration can meet 1e-3 for this checkpoint. Evaluation therefore uses the ADVISORY's "
        "no-padding path (batch size 1, no pad tokens), which is free of batch composition by construction.",
        "",
        "Open question for the operator: accept the no-padding path as satisfying acceptance item 1, or "
        "revise the tolerance to the measured fp32 noise floor (a settled threshold; not changed here).",
        "",
        "## 1. The padded-batch test (fp32, step 1,000, 8 dev items)",
        "",
        "| variant | artifact | alone vs padded batch, max abs Δ (logits) | uniform-batch control | verdict | cuDNN TF32 |",
        "|---|---|---:|---:|---|---|",
        probe_row("original code (committed HEAD d3cc79c)", "probe_head_strict_fp32.json"),
        probe_row("original code, TF32 convolutions on", "probe_head_tf32conv_fp32.json"),
        probe_row("fixed code (position ids, chunk-rounded rows)", "probe_fixed_strict_fp32.json"),
        probe_row("fixed code, TF32 convolutions on", "probe_fixed_tf32conv_fp32.json"),
        "",
        "TF32 has no effect on these numbers (identical values with it on and off), so the earlier "
        "explanation that TF32 convolutions caused the residual is refuted.",
        "",
        "## 2. Where the residual comes from (logit level, strict fp32, same 8 items)",
        "",
        f"`{'logit_control_strict_fp32.json'}`. Three layouts of each item: alone with rounded rows (the fixed "
        "code's batch-of-one), alone plus 64 inert left pads (same chunk offset and positions: the same "
        "computation in exact arithmetic, so its difference is shape noise), and the unpadded item.",
        "",
        "| comparison | max abs Δ over the 8 items |",
        "|---|---:|",
        f"| shape noise: rounded alone vs rounded alone + 64 pads | {logit['max_shift_delta']:.3e} |",
        f"| the probe's quantity: rounded alone vs padded batch | {logit['max_batch_delta']:.3e} |",
        f"| cost of chunk rounding: rounded alone vs unpadded | {logit['max_rounding_delta']:.3e} |",
        "",
        f"Hidden-state shape control (`{'shape_control_strict_fp32.json'}`): last-layer maximum "
        f"{shape['max_abs_delta_per_layer'][-1]:.3e} for alone vs alone + 64 pads.",
        "",
        "Reading: the padded-batch residual (1.92e-3) is the same size as the shape-only noise floor "
        "(1.50e-3), so 1e-3 is below what this fp32 model reproduces under any change of sequence length. "
        "Rounding rows to the chunk length adds a further perturbation of up to 4.1e-3 relative to the "
        "unpadded computation. That is why the no-padding path is used for evaluation.",
        "",
        "## 3. Effect on the test split (student_v0 step 1,000, bf16, stored calibration)",
        "",
        "| scoring | artifact | micro acc | macro acc | micro Brier |",
        "|---|---|---:|---:|---:|",
    ]
    labels = {
        "old": "student_v0 run: original code, batch 16",
        "fixed16": "fixed code, batch 16 (same batch plan)",
        "fixed1": "fixed code, batch 1, rows chunk-rounded",
        "unpadded1": "fixed code, batch 1, no padding (adopted path)",
    }
    for key in ("old", "fixed16", "fixed1", "unpadded1"):
        s = scor[key]
        lines.append(f"| {labels[key]} | `{inputs[key]['path']}` | {s['micro_accuracy']:.4f} | "
                     f"{s['macro_accuracy']:.4f} | {s['micro_brier']:.4f} |")
    lines += [
        "",
        f"Every scoring has {scor['old']['n']} items; the item sets are identical. Each input's sha256 is "
        "in `outputs/student_v1/V2/effect.json`.",
        "",
        "### Paired differences (A - B)",
        "",
        "| comparison | micro accuracy | macro accuracy | micro Brier | predictions changed |",
        "|---|---|---|---|---:|",
    ]
    for key, c in effect["comparisons"].items():
        lines.append(
            f"| {key} | {pts(c['micro_accuracy_diff'])} | {pts(c['macro_accuracy_diff'])} | "
            f"{c['micro_brier_diff']['point']:+.5f} [{c['micro_brier_diff']['ci_lo']:+.5f}, "
            f"{c['micro_brier_diff']['ci_hi']:+.5f}] | {c['argmax_changed_total']} |"
        )
    lines += [
        "",
        "### Largest per-template changes, adopted path against the original batched path",
        "",
        "| template | n | accuracy Δ (pts) | 95% CI (pts) | predictions changed | correct→wrong / wrong→correct |",
        "|---|---:|---:|---|---:|---|",
        top_rows,
        "",
        "Reading: the padding bug changes the predicted label for 151 of 37,289 test items (0.4%). "
        "Micro accuracy moves by less than a tenth of a point, with a CI that includes zero. The "
        "largest per-template change (pubmedqa, 5 items, all correct→wrong) has a CI that excludes "
        "zero. With about 25 templates, one such interval is expected by chance, so it is reported "
        "as an observation and not as an effect.",
        "",
        "## 4. Verification",
        "",
        f"Fresh-process re-derivation (`scripts/student/v2_rederive_effect.py`, plain Python, no "
        f"`meddecide` import): `{rederive}`.",
        "",
        "Reproduction check: the original-run row count is 37,289 and its recomputed micro accuracy "
        f"({scor['old']['micro_accuracy']:.4f}) matches the stored tier-1 + fresh totals "
        "(13,521 + 23,768 items) in `outputs/student_v0/S9_run3/model_meddecide-0p8b-lora-pointer__test.json`.",
        "",
        "## 5. What changed in the code",
        "",
        "- `MedDecideModel.hidden_states` passes explicit `position_ids` counted from the attention mask.",
        "- `collate` rounds the row length to a multiple of `LINEAR_ATTENTION_CHUNK` (64) by default; "
        "`round_to_chunk=False` gives a row exactly as long as its longest item (no padding at batch 1).",
        "- `score_items` and `run_student.py --no-chunk-rounding` expose the switch; defaults are unchanged for training.",
        "- Tests: `tests/test_collate_unpadded.py` (layout), `tests/test_paired.py` (metrics), and "
        "`tests/test_padding_trained.py` (the probe as a strict expected failure, reason cites this file).",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
