#!/usr/bin/env python
"""Render loops/student_v1/g1.md and loops/student_v1/arms.md from the V9 artifacts (derived, R9; do not edit by hand).

Inputs, all under outputs/student_v1/V9 unless stated:
  * arm predictions, run_student format: arm_a/, arm_b/, arm_c/ (preds_meddecide-v1-arm-*__test.jsonl);
  * the G1 report of each arm (g1_arm_a.json, g1_arm_b.json, g1_arm_c.json, from scripts/bench/g1.py);
  * the arm-pair report (pairs_abc.json, from scripts/student/v9_arms.py);
  * the v0.2 test items (test_items.jsonl): the tier of each item.
The student_v0 reference row is read from its G1 report (loops/student_v1/g1_student_v0_rerun.md).

Every missing input is written as NOT MEASURED with the reason, never as a number (R3).
Usage: ``uv run python scripts/student/v9_report.py``
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

V9 = ROOT / "outputs" / "student_v1" / "V9"
LOOP = ROOT / "loops" / "student_v1"
ARMS = {
    "A (pointer head)": V9 / "arm_a" / "preds_meddecide-v1-arm-a__test.jsonl",
    "B (letter readout)": V9 / "arm_b" / "preds_meddecide-v1-arm-b__test.jsonl",
    "C (Unsloth decision head)": V9 / "arm_c" / "preds_meddecide-v1-arm-c__test.jsonl",
}
G1 = {
    "A (pointer head)": V9 / "g1_arm_a.json",
    "B (letter readout)": V9 / "g1_arm_b.json",
    "C (Unsloth decision head)": V9 / "g1_arm_c.json",
}
PAIRS = V9 / "pairs_abc.json"
ITEMS = V9 / "test_items.jsonl"
HELD_OUT = (
    "ct_phase_choice_v1",
    "fda_boxed_warning_noul_v1",
    "pubmed_humans_noul_v1",
    "ct_arm_role_noul_v1",
)
SELECTIVE = (0.5, 0.8, 0.9)


def load_items() -> dict[str, dict]:
    items = {}
    with ITEMS.open(encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            items[row["item_id"]] = {"tier": row["tier"], "template": row["template_id"]}
    return items


def load_preds(path: Path) -> dict[str, dict]:
    rows = {}
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            probs = np.asarray(row["option_probs"], dtype=np.float64)
            rows[row["item_id"]] = {
                "template": row["template_id"],
                "correct": bool(row["correct"]),
                "confidence": float(probs.max()),
                "latency": row.get("latency_s"),
            }
    return rows


def tier_of(items: dict[str, dict], item_id: str) -> str:
    return items[item_id]["tier"]


def not_measured(reason: str) -> str:
    return f"NOT MEASURED — {reason}"


def g1_section(name: str, path: Path) -> list[str]:
    if not path.exists():
        return [f"### {name}", "", not_measured(f"no G1 report at {path.relative_to(ROOT)}"), ""]
    report = json.loads(path.read_text(encoding="utf-8"))
    lines = [f"### {name}", "", "| set | verdict | detail |", "|---|---|---|"]
    for set_name, value in report["verdicts"].items():
        verdict, reason = value[0], value[1] if len(value) > 1 else ""
        lines.append(f"| `{set_name}` | {verdict} | {reason} |")
    excluded = sorted({c["template_id"] for c in report.get("excluded_cells", []) if c.get("tier") == "fresh"})
    lines += ["", f"- D12-excluded fresh cells (dropped from the verdict): "
              f"{', '.join(f'`{t}`' for t in excluded) if excluded else 'none'}.", ""]
    return lines


def student_v0_reference() -> list[str]:
    path = LOOP / "g1_student_v0_rerun.md"
    if not path.exists():
        return ["### Reference row: student_v0 (step 1,000, fixed path)", "",
                not_measured("no student_v0 G1 report found"), ""]
    text = path.read_text(encoding="utf-8")
    verdict_lines = [line for line in text.split("\n") if line.startswith("| G1") or line.startswith("| **G1")]
    return ["### Reference row: student_v0 (step 1,000, fixed path; labelled as a reference)", "",
            f"Source: `{path.relative_to(ROOT)}` (claims V011-V014). Verdict rows copied from that report:", "",
            *verdict_lines, ""]


def g1_md() -> str:
    lines = ["# G1 — student_v1 arms against the baselines (V9)", "",
             "Generated by `scripts/student/v9_report.py` from `outputs/student_v1/V9`. Do not edit by hand.", "",
             "Each arm's full G1 report is `loops/student_v1/g1_arm_*.md`; the verdict rule (D16) and the D12 gate are "
             "applied there. Only D12-passing cells enter a verdict. Verdicts vs zero-shot and vs JEV-9B are shown per "
             "arm and per set.", ""]
    for name, path in G1.items():
        lines += g1_section(name, path)
    lines += student_v0_reference()
    return "\n".join(lines) + "\n"


def pair_block(label: str, block: dict) -> list[str]:
    if "status" in block:
        return [f"- {label}: {block['status']}"]
    out = [f"- {label}: n = {block['n']} items over {block['templates']} templates."]
    for key, name in (("macro_accuracy_diff", "macro accuracy"), ("micro_accuracy_diff", "micro accuracy"),
                      ("mean_brier_diff", "mean Brier")):
        d = block[key]
        out.append(f"  - {name}: {d['point']:+.4f} [{d['ci_lo']:+.4f}, {d['ci_hi']:+.4f}]")
    return out


def accuracy_cell(arm: dict[str, dict], ids: list[str]) -> str:
    if not ids:
        return "NOT MEASURED"
    return f"{np.mean([arm[i]['correct'] for i in ids]):.4f} (n={len(ids)})"


def arms_md(items: dict[str, dict], preds: dict[str, dict[str, dict]]) -> str:
    lines = ["# arms — student_v1 arm-vs-arm, per-template, selective accuracy and latency (V9)", "",
             "Generated by `scripts/student/v9_report.py` from `outputs/student_v1/V9`. Do not edit by hand.", "",
             "## 1. Arm-vs-arm paired comparisons", "",
             "Difference = left arm minus right arm (paired bootstrap, 2,000 resamples, 95 % percentile interval). "
             "Verdict scope: fresh tier, with the templates G1 excluded under D12 dropped (ADVISORY V9). The "
             "all-tier comparison without D12 exclusions is additional and is not a verdict.", ""]
    if PAIRS.exists():
        pairs = json.loads(PAIRS.read_text(encoding="utf-8"))
        for key, pair in pairs["pairs"].items():
            v = pair["verdict"]
            lines.append(f"### {key}: verdict scope (tier {v['tier']}, {v['items']} items; D12-excluded templates "
                         f"dropped: {', '.join(v['excluded_templates']) or 'none'})")
            lines += pair_block("seen templates", v["seen"])
            lines += pair_block("held-out templates (D14)", v["held_out"])
            add = pair["additional_all_tiers_no_d12"]
            lines.append("- additional, all tiers and no D12 exclusions (not a verdict):")
            lines += ["  " + line for line in pair_block("seen templates", add["seen"])]
            lines += ["  " + line for line in pair_block("held-out templates", add["held_out"])]
            lines.append("")
    else:
        lines += [not_measured("no arm-pair report (run scripts/student/v9_arms.py)"), ""]

    lines += ["## 2. Accuracy overall and per template (test items; the fresh tier is the verdict scope)", "",
              "### Overall accuracy (all test items, and by tier)", "",
              "| arm | all items | fresh tier | established tier |", "|---|---:|---:|---:|"]
    for name, arm in preds.items():
        fresh = [i for i in arm if tier_of(items, i) == "fresh"]
        established = [i for i in arm if tier_of(items, i) == "established"]
        cells = [accuracy_cell(arm, ids) for ids in (list(arm), fresh, established)]
        lines.append(f"| {name} | " + " | ".join(cells) + " |")
    lines.append("")
    lines += ["### Per template", ""]
    templates = sorted({items[i]["template"] for arm in preds.values() for i in arm})
    header = "| template | tier | n | " + " | ".join(f"{a} acc" for a in preds) + " |"
    lines += [header, "|---|---|---:|" + "---:|" * len(preds)]
    for template in templates:
        ids = [i for i in next(iter(preds.values())) if items[i]["template"] == template]
        tier = items[ids[0]]["tier"] if ids else ""
        row = [f"`{template}`", tier, str(len(ids))]
        for arm in preds.values():
            hits = [arm[i]["correct"] for i in ids if i in arm]
            row.append(f"{np.mean(hits):.4f}" if hits else "NOT MEASURED")
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")

    lines += ["## 3. Selective accuracy (additional; all test items; items ranked by their top option probability)", "",
              "| arm | " + " | ".join(f"{int(c * 100)} % coverage" for c in SELECTIVE) + " |",
              "|---|" + "---:|" * len(SELECTIVE)]
    for name, arm in preds.items():
        ranked = sorted(arm.values(), key=lambda r: -r["confidence"])
        cells = []
        for coverage in SELECTIVE:
            k = max(1, round(coverage * len(ranked)))
            cells.append(f"{np.mean([r['correct'] for r in ranked[:k]]):.4f} (n={k})")
        lines.append(f"| {name} | " + " | ".join(cells) + " |")
    lines.append("")

    lines += ["## 4. Latency per question (additional; wall-clock per scored item, median and 90th percentile)", ""]
    lines += ["| arm | median s | p90 s | per record |", "|---|---:|---:|---|"]
    for name, arm in preds.items():
        lat = [r["latency"] for r in arm.values() if r["latency"] is not None]
        if lat:
            lines.append(f"| {name} | {np.median(lat):.4f} | {np.percentile(lat, 90):.4f} | "
                         f"{not_measured('the scoring path is one item per call; no per-record timing was recorded')} |")
        else:
            lines.append(f"| {name} | NOT MEASURED | NOT MEASURED | NOT MEASURED |")
    lines.append("")

    lines += ["## 5. Not measured in this loop", "",
              f"- option-shuffle flip rate: {not_measured('needs re-scoring with permuted options on the GPU; not run')}.",
              f"- HLE (supplementary, `data/bench/v0.2/supplementary/hle_med.jsonl`): "
              f"{not_measured('the three arms have not been scored on it; not run')}.",
              f"- long-record slice (v0.2 definition, `data/bench/v0.2/long_record.json`): "
              f"{not_measured('the slice membership is not stored in the items; the counts file predates the screen drop of 495 items')}. "
              "An approximation, the items whose prompt reaches the 8,192-token cap (V102), is in the arm predictions "
              "but is not reported here as the slice.",
              f"- tier-1 G1 (`--tier1`): {not_measured('not requested for the arm G1 runs; per-tier accuracy is in section 2')}.",
              f"- per-record latency: {not_measured('no record-level timing was recorded')}.", ""]
    return "\n".join(lines) + "\n"


def main() -> None:
    items = load_items()
    preds: dict[str, dict[str, dict]] = {}
    for name, path in ARMS.items():
        if path.exists():
            preds[name] = load_preds(path)
    (LOOP / "g1.md").write_text(g1_md(), encoding="utf-8")
    (LOOP / "arms.md").write_text(arms_md(items, preds), encoding="utf-8")
    print("wrote loops/student_v1/g1.md and loops/student_v1/arms.md with", len(preds), "arm prediction files")


if __name__ == "__main__":
    main()
