"""Write the O10 configs (Osler-9B and Osler-0.8B) from arm L's recipe and O9's head choice (ADVISORY O10). CPU only.

Reads configs/osler_v0/arm_L.yaml and outputs/osler_v0/O9/head_choice.json, writes configs/osler_v0/osler_9b.yaml and
configs/osler_v0/osler_0p8b.yaml, and checks each written file with the O10 driver's own guards (pinned base, O9's head,
arm L's recipe). Generated files: regenerate, do not edit by hand.

Usage:
    uv run --frozen python scripts/osler/o10_write_configs.py
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import yaml

from meddecide.train.config import load_config
from meddecide.train.osler_configs import (
    check_head_matches,
    check_pinned_base,
    o10_config_data,
    recipe_differences,
)

REPO = Path(__file__).resolve().parents[2]
REFERENCE = REPO / "configs/osler_v0/arm_L.yaml"
HEAD_CHOICE = REPO / "outputs/osler_v0/O9/head_choice.json"
TARGETS = (
    ("Qwen/Qwen3.5-9B", "outputs/osler_v0/O10/osler_9b", "configs/osler_v0/osler_9b.yaml"),
    ("Qwen/Qwen3.5-0.8B", "outputs/osler_v0/O10/osler_0p8b", "configs/osler_v0/osler_0p8b.yaml"),
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--head-choice", type=Path, default=HEAD_CHOICE)
    parser.add_argument("--out-dir", type=Path, default=REPO / "configs/osler_v0", help=argparse.SUPPRESS)  # tests only
    args = parser.parse_args()
    chosen = str(json.loads(args.head_choice.read_text(encoding="utf-8"))["chosen"])
    reference_data = yaml.safe_load(REFERENCE.read_text(encoding="utf-8"))
    reference_sha = sha256(REFERENCE)
    choice_sha = sha256(args.head_choice)
    for base_model, output_dir, target in TARGETS:
        data = o10_config_data(reference_data, base_model=base_model, output_dir=output_dir, chosen=chosen)
        header = (
            f"# O10 config (ADVISORY O10): {base_model}, head {chosen} (O9's choice), the O6-O8 recipe.\n"
            f"# Generated by scripts/osler/o10_write_configs.py from configs/osler_v0/arm_L.yaml (sha256 {reference_sha})\n"
            f"# and {args.head_choice.name} (sha256 {choice_sha}). Regenerate; do not edit by hand.\n"
        )
        path = args.out_dir / Path(target).name
        path.write_text(header + yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
        config = load_config(path)
        check_pinned_base(config)
        check_head_matches(config, chosen)
        differences = recipe_differences(config, load_config(REFERENCE))
        if differences:
            raise SystemExit(f"{target}: the recipe differs from arm L in {differences}")
        print(f"wrote {path}: base {base_model}, head {chosen}, output {output_dir}, lora r={config.lora.r}; "
              "guards passed", flush=True)


if __name__ == "__main__":
    main()
